Fix mac build
"errno.h" doesn't get included on mac so we need to do it explicitely.

system/core/libnativebridge/tests/CodeCacheExists_test.cpp:30:15: error:
use of undeclared identifier 'ENOENT'
      ASSERT_EQ(ENOENT, errno);

(cherry picked from commit bcd1a834d4a979ae650ac8677b0647cfb3ec4766)

Change-Id: Ib894e3a3912a943c61787461f127e4b11aacf212